version: '3.3'

services:
  prometheus:
    image: prom/prometheus:v2.5.0
    volumes:
      - './prometheus/:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  node-exporter:
    image: prom/node-exporter:v0.17.0
    ports:
      - 9100:9100
    volumes:
      - '/proc:/host/proc'
      - '/sys:/host/sys'
      - '/:/rootfs'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 10M
  
  alertmanager:
    image: prom/alertmanager:v0.15.3
    ports: 
      - 9093:9093
    volumes:
      - './alertmanager/conf/:/prometheus/'
      - './alertmanager/data:/data'
    command:
      - '--config.file=/prometheus/config.yml'
      - '--storage.path=/data'
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    
  cadvisor:
    image: google/cadvisor:v0.32.0
    ports: 
      - 8080:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  
  blackbox_exporter:
    image: prom/blackbox-exporter:v0.12.0
    ports:
      - 9115:9115
    dns:
      - 192.168.2.5
      - 192.168.2.10
    volumes:
      - './blackbox-exporter:/config'
    command: 
      - '--config.file=/config/blackbox.yml'
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  
  remotestorageadapter:
    image: gavind/prometheus-remote-storage-adapter:1.0
    ports:
      - 9201:9201
    environment:
      - INFLUXDB_PW=prometheus
    command:
      - '-influxdb-url=http://192.168.252.64:8086'
      - '-influxdb.database=promedb'
      - '-influxdb.retention-policy=autogen'
      - '-influxdb.username=prome'
  noti-webhook:
    image: dukecyber/pwebhook:v1.0.0
    ports:
      - 5000:5000
# networks:
#   outside:
#     external:
#       name: "host"