version: '3.3'

services:
  grafana:
    image: grafana/grafana
    network_mode: "host"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
      - "./grafana/plugin/:/var/lib/grafana/plugins/"
      - "./grafana/custom.ini:/etc/grafana/custom.ini"
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  unsee:
    image: cloudflare/unsee:v0.8.0
    network_mode: "host"
    ports:
      - 9094:8080
    environment:
      - "ALERTMANAGER_URIS=default:http://192.168.252.61:9093"
    deploy:
      mode: replicated
      replicas: 1

# networks:
#   outside:
#     external:
#       name: "host"