version: '3.3'

services:
  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
      - "./grafana/plugin/:/var/lib/grafana/plugins/"
      - "./grafana/custom.ini:/etc/grafana/custom.ini"
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30
    # deploy:
    #     mode: replicated
    #     replicas: 1
    #     restart_policy:
    #       condition: on-failure
    #       delay: 5s
    #       max_attempts: 3
    #       window: 120s