global:
  scrape_interval:     30s
  evaluation_interval: 1m
  external_labels:
    monitor: 'ptvn-prom'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "192.168.252.61:9093"

rule_files:
  - "alert.rules"

remote_write:
  - url: "http://192.168.252.61:9201/write"

remote_read:
  - url: "http://192.168.252.61:9201/read"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    dns_sd_configs:
    - names:
      - 'tasks.prometheus-cen'
      type: 'A'
      port: 9090
    static_configs:
      - targets: ['192.168.252.61:9090']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.252.61:9100','192.168.10.219:9100','192.168.10.196:9100','192.168.252.64:9100']
        labels:
          group: 'test-node-linux'
          projects: 'Demo2'
  
  - job_name: 'influx-exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.252.64:9100']
        labels:
          group: 'influxdb-linux'
          projects: 'Demo2'

  - job_name: 'node-gz'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.5.121:9100','192.168.10.74:9100']
        labels:
          group: 'gz-node-linux'
          projects: 'Goodchoize'
  
  - job_name: 'node-op-uat'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.135.19:9100','192.168.135.54:9100']
        labels:
          group: 'opuat-node-linux'
          projects: 'Oneplanet'

  - job_name: 'wmi-exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.10.164:9182','192.168.10.241:9182']
        labels:
          group: 'test-node-windows'
          projects: 'Demo1'
  
  - job_name: 'wmi-gz'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - '192.168.5.107:9182'
          - '192.168.5.109:9182'
          - '192.168.5.122:9182'
          - '192.168.5.117:9182'
          - '192.168.5.119:9182'
          - '192.168.5.209:9182'
          - '192.168.5.233:9182'
          - '192.168.10.237:9182'
          - '192.168.10.236:9182'
          - '192.168.10.245:9182'
          - '192.168.10.247:9182'
          - '192.168.10.230:9182'
          - '192.168.10.239:9182'
          - '192.168.10.139:9182'
          - '192.168.7.23:9182'
          - '192.168.2.14:9182'
          - '192.168.2.11:9182'
        labels:
          group: 'gz-node-windows'
          projects: 'Goodchoize'
  
  - job_name: 'tomcat-exporter'
    scrape_interval: 10s
    scrape_timeout: 10s
    dns_sd_configs:
    - names:
      - 'tasks.tomcat-exporter'
      type: 'A'
      port: 8080
    static_configs:
      - targets: ['192.168.19.39:8080']
        labels:
          group: 'test-tomcat-exporter'
          projects: 'Demo2'

  - job_name: 'cadvisor'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['192.168.252.61:8080','192.168.10.219:9090']
        labels:
          group: 'test-container-exporter'
          projects: 'Demo2'
  
  - job_name: 'blackbox-web'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.pantavanij.com
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=1
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=24
        - https://ep.pantavanij.com/true
        - https://www.opoversea.com/eps/Login/75
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=2
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=5
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=7
        - https://cpallep.pantavanij.com
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=14
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=48
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=52
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=59
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=68
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=72
        - https://buysite.pantavanij.com/ebd/WebDriver?ACT=Login&EID=73
        - https://tmgep.pantavanij.com
        - https://kbankep.pantavanij.com
        - http://auction.pantavanij.com
        - http://auction2.pantavanij.com
        - http://auction3.pantavanij.com
        - http://auction5.pantavanij.com
        - http://auction9.pantavanij.com
        - http://on-site.pantavanij.com
        - http://azcp.car.pantavanij.com/OALC/firstpage.action
        - http://auction10.pantavanij.com
        - http://auction11.pantavanij.com
        - http://tip.car.pantavanij.com
        - http://tnn.car.pantavanij.com
        - http://erfxonline.pantavanij.com
        - https://www.goodchoiz.com
        - https://www.makroclick.com/th
        - https://www.makro.co.th/login
        - http://192.168.252.34
        - https://trueordering.pantavanij.com
        - http://192.168.19.39:8080
        - https://www.supplierwebwork.com
        - https://cpallep.pantavanij.com
        labels:
          group: 'test-web-monitor'
          projects: 'Demo4'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.252.61:9115
