global:
  scrape_interval:     30s
  evaluation_interval: 1m
  external_labels:
    monitor: 'ptvn-prom'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

rule_files:
  # - "alert.rules"
  # - "alwindows.rules"
  # - "al-docker.rules"

remote_write:
  - url: "http://localhost:9201/write"

remote_read:
  - url: "http://localhost:9201/read"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prome-cluster'
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets: 
        - 'localhost:9100'
        labels:
          group: 'prome-swarm-linux'
          projects: 'Prometheus'
          hostname: 'prome-cluster'

  - job_name: 'blackbox-web'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.google.com
        labels:
          group: 'test-web-monitor'
          projects: 'Demo4'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.252.61:9115
