global:
  resolve_timeout: 5m

route:
  group_by: ['alertname','projects', 'group']
  group_interval: 30s
  group_wait: 45s
  repeat_interval: 6h
  receiver: 'line-noti'
  routes:
  - match_re:
      projects: Good+.*
    receiver: 'gzline-noti'

receivers:
- name: 'line-noti'
  webhook_configs:
  - url: 'http://localhost:5000/webhook'
    send_resolved: true
    http_config:
      bearer_token: 'Token'
- name: 'gzline-noti'
  webhook_configs:
  - url: 'http://localhost:5000/webhook'
    send_resolved: true
    http_config:
      bearer_token: 'Token'