global:
  resolve_timeout: 5m

route:
  receiver: 'line-noti'
  group_interval: 30m
  group_wait: 45s
  repeat_interval: 1h

receivers:
- name: 'line-noti'
  webhook_configs:
  - url: 'http://192.168.252.61:5000/webhook'
    send_resolved: true
    http_config:
      bearer_token: 's4XZKAW2k0sDzgcctusZ7PvIbkEIofTSDDcTTx6JTIS'
  - url: 'http://192.168.252.62:5000/webhook'
    http_config:
      bearer_token: 's4XZKAW2k0sDzgcctusZ7PvIbkEIofTSDDcTTx6JTIS'