global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring'