{
 "title": "Goodchoize - Linux Datacenter",
 "description": "Summarize host for Linux OS",
 "tags": [
  "prometheus",
  "node_exporter",
  "centos",
  "Goodchoize",
  "alerting"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "label_values(up,group)" }
  ]
 },
 "panels": [
  {
   "title": "Host Alive",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{group=~\"$group\"} > 0) / sum(up{group=~\"$group\"}) * 100"
    }
   ]
  },
  {
   "title": "Host Down!!",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{group=~\"test-node-linux\"} < 1)"
    }
   ]
  },
  {
   "title": "% CPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg without (mode,cpu) (rate(node_cpu_seconds_total{group=~\"$group\",mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{group=~\"$group\"}",
     "legendFormat": "CPU load 1 min on {{instance}}"
    },
    {
     "expr": "node_load5{group=~\"$group\"}",
     "legendFormat": "CPU load 5 min on {{instance}}"
    },
    {
     "expr": "node_load15{group=~\"$group\"}",
     "legendFormat": "CPU load 15 min on {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{group=~\"$group\"} - node_memory_MemAvailable_bytes{group=~\"$group\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write stat",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_disk_read_bytes_total{group=~\"$group\"} > 0",
     "legendFormat": "Read {{instance}} : {{device}}"
    },
    {
     "expr": "-(node_disk_written_bytes_total{group=~\"$group\"}) < 0",
     "legendFormat": "Write {{instance}} : {{device}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{group=~\"$group\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_time_seconds_total{group=~\"$group\"}) by (instance,device) > 0",
     "legendFormat": "{{instance}} : {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes", "label": "Rx < ------ > Tx" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{group=~\"$group\",device!=\"lo\"}[5m]) > 0",
     "legendFormat": "Tx {{instance}} : {{device}}"
    },
    {
     "expr": "- rate(node_network_receive_bytes_total{group=~\"$group\",device!=\"lo\"}[5m]) < 0",
     "legendFormat": "Rx {{instance}} : {{device}}"
    }
   ]
  }
 ]
}