{
 "title": "All - Docker cluster monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "docker",
  "swarm"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "label_values(up,group)" },
   {
    "name": "projects",
    "label": "Projects",
    "query": "label_values(up{group=\"$group\"},projects)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(up{group=\"$group\" , projects=\"$projects\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",projects=\"$projects\", instance=~\"$server.*\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", projects=\"$projects\", instance=~\"$server.*\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", projects=\"$projects\", instance=~\"$server.*\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", projects=\"$projects\", instance=~\"$server.*\"}[5m]) * 100) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=~\"$server.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\", instance=~\"$server.*\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\", instance=~\"$server.*\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}