{
 "title": "All - Windows Node",
 "description": "General stats dashboard with node selector, uses metrics from wmi_exporter",
 "tags": [
  "windows",
  "wmi_exporter",
  "prometheus",
  "Demo1",
  "clients"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   { "name": "group", "label": "Group", "query": "label_values(up,group)" },
   {
    "name": "projects",
    "label": "Projects",
    "query": "label_values(up{group=\"$group\"},projects)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(up{group=\"$group\",projects=\"$projects\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{projects=~\"$projects\", instance=~\"$server.*\"}"
    }
   ]
  },
  {
   "title": "System resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum by (mode) (rate(wmi_cpu_time_total{instance=~\"$server.*\" , projects=\"$projects\"}[5m]))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{mode}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "system_threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "wmi_system_threads{instance=~\"$server.*\", projects=\"$projects\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "system_threads",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "System exception dispatches",
     "type": "graph",
     "description": "Rate of exceptions dispatched by the system.This property displays the difference between the values observed in the last two samples, divided by the duration of the sample interval.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(wmi_system_exception_dispatches_total{instance=~\"$server.*\", projects=\"$projects\"}[$interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "exceptions",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "wmi_os_virtual_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Virtual memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "wmi_cs_physical_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Physical memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Free physical memory",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Process Total",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "wmi_os_processes{instance=~\"$server.*\", projects=\"$projects\"}"
      }
     ]
    },
    {
     "title": "Time of service process",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "topk(20, sum(rate(wmi_process_cpu_time_total{process!=\"Idle\",instance=~\"$server.*\", projects=\"$projects\"}[5m])) by (instance,mode,process))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{process}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Hard drive load",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(wmi_logical_disk_write_bytes_total{instance=~\"$server.*\", projects=\"$projects\", volume !~\"HarddiskVolume.+\"}[$interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "- irate(wmi_logical_disk_read_bytes_total{instance=~\"$server.*\", projects=\"$projects\", volume !~\"HarddiskVolume.+\"}[$interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Hard disk i/o ops total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(wmi_logical_disk_split_ios_total{instance=~\"$server.*\", projects=\"$projects\", volume !~\"HarddiskVolume.+\"}[30s])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "i/o {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Hard disk free space",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "wmi_logical_disk_free_bytes{instance=~\"$server.*\", projects=\"$projects\", volume !~\"HarddiskVolume.+\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "free {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(wmi_net_bytes_sent_total{instance=~\"$server.*\", projects=\"$projects\"}[$interval]) >0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Sent {{nic}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "- rate(wmi_net_bytes_received_total{instance=~\"$server.*\", projects=\"$projects\"}[$interval]) <0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Received {{nic}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "IIS monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application pool running",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(wmi_iis_current_application_pool_state{instance=~\"$server.*\", projects=\"$projects\" ,state=\"Running\"} > 0)"
      }
     ]
    },
    {
     "title": "Worker process succuess.",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(max(wmi_iis_recent_worker_process_failures) by (instance,app) < 1)"
      }
     ]
    },
    {
     "title": "Logon attempts",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_iis_logon_attempts_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "{{site}}"
      }
     ]
    },
    {
     "title": "Data send and receive",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_iis_received_bytes_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Received {{site}}"
      },
      {
       "expr": "rate(wmi_iis_sent_bytes_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Send {{site}}"
      }
     ]
    },
    {
     "title": "Anonymous user total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_iis_anonymous_users_total{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{site}}"
      }
     ]
    },
    {
     "title": "Requests (GET/POST)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_iis_requests_total{instance=~\"$server.*\", projects=\"$projects\",method=\"POST\"}[5m])",
       "legendFormat": "{{site}}/{{method}}"
      },
      {
       "expr": "rate(wmi_iis_requests_total{instance=~\"$server.*\", projects=\"$projects\",method=\"GET\"}[5m])",
       "legendFormat": "{{site}}/{{method}}"
      }
     ]
    },
    {
     "title": "Attempts connection instance total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_iis_connection_attempts_all_instances_total{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{site}}"
      }
     ]
    },
    {
     "title": "Anonymous user current",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_iis_current_anonymous_users{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{site}}"
      }
     ]
    },
    {
     "title": "IIS files tranfering",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_iis_files_sent_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Sent {{site}}"
      },
      {
       "expr": "- rate(wmi_iis_files_received_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Received {{site}}"
      }
     ]
    },
    {
     "title": "ISAPI extension requests",
     "type": "graph",
     "description": "ISAPI extensions are true applications that run on IIS and have access to all of the functionality provided by IIS. As an example of how powerful ISAPI extensions can be, ASP pages are processed through an ISAPI extension called ASP.dll. In general, clients can access ISAPI extensions the same way they access a static HTML file or dynamic ASP file.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_iis_current_isapi_extension_requests{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{site}}"
      }
     ]
    },
    {
     "title": "Current connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_iis_current_connections{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{site}}"
      }
     ]
    },
    {
     "title": "IIS Worker processes",
     "type": "graph",
     "description": "An IIS Worker Process (w3wp.exe) handles the web requests sent to the IIS web server for the configured IIS application pool",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_iis_current_worker_processes{instance=~\"$server.*\", projects=\"$projects\"} > 0",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MSSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active transaction database",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(wmi_mssql_databases_active_transactions{instance=~\"$server.*\", projects=\"$projects\"}) * 100"
      }
     ]
    },
    {
     "title": "Service state",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(count(wmi_mssql_collector_success{instance=~\"$server.*\", projects=\"$projects\"} > 0)) / count(wmi_mssql_collector_success{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "Restore backup database",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(wmi_mssql_databases_backup_restore_operations{instance=~\"$server.*\", projects=\"$projects\"}) * 100"
      }
     ]
    },
    {
     "title": "Time to wait for page",
     "type": "singlestat",
     "description": "Number of times a reader needs to wait for a page because the InSysXact bit is set.",
     "gridPos": { "h": 4, "w": 6, "x": 14, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(wmi_mssql_accessmethods_insysxact_waits{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "Commit table database",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(wmi_mssql_databases_commit_table_entries{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "SQL memory manager",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_memmgr_free_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Free memory"
      },
      {
       "expr": "wmi_mssql_memmgr_connection_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Connection memory"
      },
      {
       "expr": "wmi_mssql_memmgr_optimizer_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Optimizer memory"
      },
      {
       "expr": "wmi_mssql_memmgr_log_pool_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Log pool memory"
      },
      {
       "expr": "wmi_mssql_memmgr_sql_cache_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Cache memory"
      },
      {
       "expr": "wmi_mssql_memmgr_stolen_server_memory_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Store other memory"
      }
     ]
    },
    {
     "title": "Parameterization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_sqlstats_auto_parameterization_attempts{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Auto"
      },
      {
       "expr": "rate(wmi_mssql_sqlstats_failed_auto_parameterization_attempts{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Failed auto"
      },
      {
       "expr": "rate(wmi_mssql_sqlstats_safe_auto_parameterization_attempts{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Safe auto"
      },
      {
       "expr": "rate(wmi_mssql_sqlstats_unsafe_auto_parameterization_attempts{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Unsafe auto"
      }
     ]
    },
    {
     "title": "Genstat connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_genstats_connection_resets{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "reset connection"
      },
      {
       "expr": "rate(wmi_mssql_genstats_logical_connections{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Logical connection"
      },
      {
       "expr": "rate(wmi_mssql_genstats_user_connections{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "User connection"
      }
     ]
    },
    {
     "title": "SQL attention",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_sqlstats_sql_attentions{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Attentions"
      },
      {
       "expr": "rate(wmi_mssql_sqlstats_sql_compilations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Compilations"
      },
      {
       "expr": "rate(wmi_mssql_sqlstats_sql_recompilations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Recompilations"
      }
     ]
    },
    {
     "title": "SQL locks stat",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_locks_lock_waits{instance=~\"$server.*\", projects=\"$projects\"}[5m]) > 0",
       "legendFormat": "Lock {{resource}} waits"
      },
      {
       "expr": "rate(wmi_mssql_locks_lock_timeouts{instance=~\"$server.*\", projects=\"$projects\"}[5m]) > 0",
       "legendFormat": "Lock {{resource}} timeout"
      },
      {
       "expr": "rate(wmi_mssql_locks_lock_requests{instance=~\"$server.*\", projects=\"$projects\"}[5m]) > 0",
       "legendFormat": "Lock {{resource}} request"
      }
     ]
    },
    {
     "title": "SQL deadlock total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_genstats_mars_deadlocks{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "MARS deadlocks"
      },
      {
       "expr": "wmi_mssql_locks_deadlocks{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{resource}} deadlocks"
      }
     ]
    },
    {
     "title": "Database transaction",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_databases_transactions{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Genstat login/logout",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_genstats_logins{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Logins"
      },
      {
       "expr": "rate(wmi_mssql_genstats_logouts{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Logouts"
      }
     ]
    },
    {
     "title": "Log pool request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_databases_log_pool_requests{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Log usage %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_databases_log_used_percent{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Bulk copy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_databases_bulk_copy_bytes{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "{{database}} bytes/sec"
      },
      {
       "expr": "rate(wmi_mssql_databases_bulk_copy_rows{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "{{database}} rows/sec"
      }
     ]
    },
    {
     "title": "Database log file size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_databases_log_files_size_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Total :{{database}}"
      },
      {
       "expr": "wmi_mssql_databases_log_files_used_size_bytes{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "Use :{{database}}"
      }
     ]
    },
    {
     "title": "Pages allocates",
     "type": "graph",
     "description": "Number of pages allocated per second in all databases in this instance of SQL Server. These include pages allocations from both mixed extents and uniform extents.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_page_allocations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Allocates"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_page_deallocations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Deallocates"
      }
     ]
    },
    {
     "title": "Page splits",
     "type": "graph",
     "description": "Number of page splits per second that occur as the result of overflowing index pages.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_page_splits{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Page split"
      }
     ]
    },
    {
     "title": "Qualified scan",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_probe_scans{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Probe scan"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_range_scans{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Range scan"
      }
     ]
    },
    {
     "title": "LOB handle",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_lob_handle_destroys{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Destroys"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_lob_handle_creates{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Create"
      }
     ]
    },
    {
     "title": "LOB provider",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_lob_ss_provider_creates{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Create"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_lob_ss_provider_destroys{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Destroy"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_lob_ss_provider_truncations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Truncation"
      }
     ]
    },
    {
     "title": "Mixed page",
     "type": "graph",
     "description": "Number of pages allocated per second from mixed extents. These could be used for storing the IAM pages and the first eight pages that are allocated to an allocation unit.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_mixed_page_allocations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Mixed page allocated"
      }
     ]
    },
    {
     "title": "Ghost record skipped",
     "type": "graph",
     "description": "In the leaf level of an index, when rows are deleted, they're marked as ghost records. This means that the row stays on the page but a bit is changed in the row header to indicate that the row is really a ghost.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_ghost_record_skips{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Ghost record"
      }
     ]
    },
    {
     "title": "Index searches / sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_index_searches{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Search index"
      }
     ]
    },
    {
     "title": "Space scan / sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
     "yaxes": [
      { "format": "short", "label": "counts / sec" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_free_space_page_fetches{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Fetches scan"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_free_space_scans{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Free scan"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_full_scans{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Full scan"
      }
     ]
    },
    {
     "title": "Extent allocate / deallocate",
     "type": "graph",
     "description": "Number of extents allocated or deallocated per second in all databases in this instance of SQL Server.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "counts / sec" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_extent_allocations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Allocated"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_extent_deallocations{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Deallocated"
      }
     ]
    },
    {
     "title": "Records forwarding in sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "record / sec" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_forwarded_records{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Forwarding"
      }
     ]
    },
    {
     "title": "Column push / pull values",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(wmi_mssql_accessmethods_column_value_pushes{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Pushes"
      },
      {
       "expr": "rate(wmi_mssql_accessmethods_column_value_pulls{instance=~\"$server.*\", projects=\"$projects\"}[5m])",
       "legendFormat": "Pulls"
      }
     ]
    },
    {
     "title": "Collector duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_collector_duration_seconds{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "By-reference lob create and uses",
     "type": "graph",
     "description": "lob => Large Object values",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wmi_mssql_accessmethods_by_reference_lob_creates{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "lob create"
      },
      {
       "expr": "wmi_mssql_accessmethods_by_reference_lob_uses{instance=~\"$server.*\", projects=\"$projects\"}",
       "legendFormat": "lob use"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat connection info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat info",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "tomcat_info{instance=~\"$server.*\", projects=\"$projects\"}"
      }
     ]
    },
    {
     "title": "Active threads",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 2, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(tomcat_threads_active_total{instance=~\"$server.*\", projects=\"$projects\",name=\"http-nio-8080\"})"
      }
     ]
    },
    {
     "title": "Max threads",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(tomcat_threads_max{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "Java daemon threads",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_threads_daemon{instance=~\"$server.*\", projects=\"$projects\"}"
      }
     ]
    },
    {
     "title": "Java current threads",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_threads_current{instance=~\"$server.*\", projects=\"$projects\"}"
      }
     ]
    },
    {
     "title": "Java deadlock threads",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 18, "y": 10 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jvm_threads_deadlocked{instance=~\"$server.*\", projects=\"$projects\"}"
      }
     ]
    },
    {
     "title": "Traffic send/recv",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "idelta(tomcat_requestprocessor_sent_bytes{instance=~\"$server.*\", projects=\"$projects\",name=\"http-nio-8080\"}[5m])",
       "legendFormat": "Sent HTTP"
      },
      {
       "expr": "idelta(tomcat_requestprocessor_received_bytes{instance=~\"$server.*\", projects=\"$projects\",name=\"http-nio-8080\"}[5m])",
       "legendFormat": "Received HTTP"
      },
      {
       "expr": "idelta(tomcat_requestprocessor_sent_bytes{instance=~\"$server.*\", projects=\"$projects\",name=\"ajp-nio-8009\"}[5m])",
       "legendFormat": "Sent AJP"
      },
      {
       "expr": "idelta(tomcat_requestprocessor_received_bytes{instance=~\"$server.*\", projects=\"$projects\",name=\"ajp-nio-8009\"}[5m])",
       "legendFormat": "Received AJP"
      }
     ]
    },
    {
     "title": "Request  count / error count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(tomcat_requestprocessor_request_count{instance=~\"$server.*\", projects=\"$projects\",name=\"http-nio-8080\"}[5m])",
       "legendFormat": "Request HTTP"
      },
      {
       "expr": "idelta(tomcat_requestprocessor_error_count{instance=~\"$server.*\", projects=\"$projects\",name=\"http-nio-8080\"}[5m])",
       "legendFormat": "Error HTTP"
      },
      {
       "expr": "idelta(tomcat_requestprocessor_request_count{instance=~\"$server.*\", projects=\"$projects\",name=\"ajp-nio-8009\"}[5m])",
       "legendFormat": "Request AJP"
      },
      {
       "expr": "idelta(tomcat_requestprocessor_error_count{instance=~\"$server.*\", projects=\"$projects\",name=\"ajp-nio-8009\"}[5m])",
       "legendFormat": "Error AJP"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat servlet info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 servlets average processing time per request",
     "type": "graph",
     "description": "Top 4 servlets average processing time per request in last 5 minutes",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(5, idelta(servlet_request_seconds_count{instance=~\"$server.*\", projects=\"$projects\"}[5m]) / idelta(servlet_request_seconds_sum{instance=~\"$server.*\", projects=\"$projects\"}[5m]))",
       "legendFormat": "context:{{context}} , method:{{method}}"
      }
     ]
    },
    {
     "title": "Session count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(tomcat_session_created_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])) by (instance)",
       "legendFormat": "New"
      },
      {
       "expr": "sum(idelta(tomcat_session_expired_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])) by (instance)",
       "legendFormat": "Expired"
      },
      {
       "expr": "sum(idelta(tomcat_session_rejected_total{instance=~\"$server.*\", projects=\"$projects\"}[5m])) by (instance)",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "Session current count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(tomcat_session_active_total{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "Session alivetime avg",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(tomcat_session_alivetime_seconds_avg{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "Session total expired",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(tomcat_session_expired_total{instance=~\"$server.*\", projects=\"$projects\"})"
      }
     ]
    },
    {
     "title": "Top 5 servlet request count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, idelta(servlet_request_seconds_count{instance=~\"$server.*\", projects=\"$projects\"}[5m]))",
       "legendFormat": "context={{context}} , method={{method}}"
      }
     ]
    },
    {
     "title": "Top 5 servlet response status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, idelta(servlet_response_status_total{instance=~\"$server.*\", projects=\"$projects\"}[5m]))",
       "legendFormat": "context:{{context}} , status:{{status}}"
      }
     ]
    }
   ]
  }
 ]
}